#DataModule args:
data_path: "../cellxgene.h5t"
batch_size: 16
n_workers: 4
in_memory: False
return_zeros: False

input_processing:
  - type: RankCounts
    key: "gene_counts"

  - type: CountsPerX
    key: "gene_counts"
    factor: 10_000

  - type: FixedNorm
    key: "gene_counts"
    factor: 0.01

  - type: LogP1
    key: "gene_counts"

  - type: Bin
    bins: "../express/express/utils/bins50.txt"
    key: "gene_counts"

  - type: DuplicateCells
    affected_keys: ["gene_counts", "gene_index", "gene_counts_true"]

  - type: FilterTopGenes
    affected_keys: ["gene_counts", "gene_index", "gene_counts_true"]
    number: 1024

  - type: FilterHVG
    affected_keys: ["gene_counts", "gene_index", "gene_counts_true"]
    number: 1024

  - type: FilterRandomGenes
    affected_keys: ["gene_counts", "gene_index", "gene_counts_true"]
    number: 1024
    proportional_hvg: False

  - type: PoissonResample
    key: "gene_counts"
    clamp_1: True

  - type: GaussianResample
    key: "gene_counts"
    std: 1
  
  - type: BinomialSubsample
    key: "gene_counts"
    p: 0.75
    clamp_1: True

  - type: Mask
    p: 0.15
    key: "gene_counts"

  - type: MolecularCV
    p_to_train: 0.8


# Model args:
discrete_input: False
n_discrete_tokens: 10
gate_input: False
pseudoquant_input: False

dim: 64
depth: 4
dropout: 0.2
n_genes: 19331
lr: 0.0005
loss:
  type: BinCE
  n_bins: 10

  #type: CountMSE
  #exp_output: True
  #lib_norm: False

  #type: PoissonNLL
  #lib_norm: False
  #zero_truncated: True

  #type: NegativeBinomialNLL
  #lib_norm: False
  #fixed_dispersion: False
  #zero_truncated: True

  #type: ZeroInflatedNegativeBinomialNLL
  #lib_norm: False
  #fixed_dispersion: False

train_on_all: False

nce_loss: True
nce_dim: 64
nce_temp: 1

celltype_clf_loss: False